### ISSUE TITLE
TestInvoke Error: Invocation failed for operation

### ISSUE THREAD

**Issue by robmoorman** [nos/api-functions#1]
## Expected Behavior
The method `testInvoke` should resolve the Promise what the Smart Contract (SC) returns.

Code which calls this method:

```js
const bookmarks = await this.props.nos.testInvoke('0xe973b31b5d8cf928916f2a30a4611b2bed31af7e', 'GetBookmarks', [address])
```

The `address` is the CoZ wallet address (`AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y`).

## Current Behavior
```js
[DApp] Error: Invocation failed for operation "GetBookmarks" on "0xe973b31b5d8cf928916f2a30a4611b2bed31af7e"
```

## Possible Solution
We tried multiple encodings for the arguments passed to `testInvoke` (no result):

```js
# Code example from Discord (@DrPpr)
const addressToScriptHash = (address) => unhexlify(u.reverseHex(wallet.getScriptHashFromAddress(address)))

# Code example from dapp-neoblog
str2hexstring(address)
```

## Steps to Reproduce (for bugs)
Details: https://github.com/Cryptopians/nos-bookmark-dapp/blob/master/README.md#setup

Smart contract: https://github.com/Cryptopians/nos-bookmark-dapp/blob/master/contracts/nos_bookmark.py
JavaScript: https://github.com/Cryptopians/nos-bookmark-dapp/blob/master/src/containers/Bookmarks.js#L25

We also tried to remove/uncomment the `CheckWitness` in the smart contract.

## Context
* Running the dApp from the client
* TestInvoke via `neo-python` works as expected

## Your Environment

* Version used: latest of all dependencies
* Environment name and version: node v8.11.1
* Operating System and version (desktop or mobile): Desktop macOS 10.12.6 (Sierra), Chrome

**Comment by jeroenptrs** [comment]
@robmoorman have you tried without the `0x` in front of the scriptHash?

**Comment by robmoorman** [comment]
He @jeroenptrs doesn't work either, with, without, or any combination with the hashes mentioned up here.

I'll try to add some more dummy prove smart contract operations to check if it's something with the address string in particular.

**Comment by robmoorman** [comment]
Ok it's now the address, as the following operation also won't be invoked:

```python
def Main(operation, args):
    if operation == 'GetName':
        return NAME
```

**Comment by robmoorman** [comment]
Ok one step further, it seems that the following Promise causes the error:

```js


export default function makeTestInvokeActions(sessionId, requestId) {
  const id = generateDAppActionId(sessionId, `${ID}-${requestId}`);

  return createActions(id, ({ net, scriptHash, operation, args }) => () => {
    return testInvoke({ net, scriptHash, operation, args });
  });
}
```

https://github.com/nos/client/blob/ca7d21e0600c238ddb6e8a28d056b018b858b920/src/actions/dapps/makeTestInvokeActions.js#L30:L36

When I mock this with the code below it works:

```js
export default function makeTestInvokeActions(sessionId, requestId) {
  const id = generateDAppActionId(sessionId, `${ID}-${requestId}`);

  return createActions(id, ({ net, scriptHash, operation, args }) => () => {
    return new Promise((resolve, reject) => {
      resolve(['Some output'])
    })
  });
}
```

T.b.c.

**Comment by robmoorman** [comment]
Ok, issue with not throwing the right error message (will make a PR on the client for this).

First of all the script hash, as you said, must not include the `0x', so `e973b31b5d8cf928916f2a30a4611b2bed31af7e` in this case.

Than after a breakdown, it errors on:

```js
const { result } = await rpc.Query.invokeScript(script).execute(endpoint);
```

Error:

```
xhr.js:178 OPTIONS http://neo-nodes:30335/ net::ERR_NAME_NOT_RESOLVED
```
