### ISSUE TITLE
Validate transfer arguments

### ISSUE THREAD

**Issue by deanpress** [nos/api-functions#6]
## Expected Behavior
You should only be able to supply numerical values to asset transfer amounts, which are smaller than what's available in your account.

## Current Behavior
![image](https://user-images.githubusercontent.com/31391056/43356103-dd8213be-926a-11e8-86eb-a291405e19d3.png)

**Comment by mhuggins** [comment]
@deanpress We still prefer strings since floats are imprecise, but we can validate the *format* of the string is numeric.  BigNumber makes this easy, we actually have an `isNumeric` helper function already.

**Comment by mhuggins** [comment]
Thought this issue was on the [nos/client](https://github.com/nos/client) repo when I left my comment.  It still may be relevant for that codebase though.

**Comment by DalderupMaurice** [comment]
Validation has been added in the latest modal PR https://github.com/nos/client/pull/513
